name: T2VQA
num_epochs: 30
warmup_epochs: 2.5
save_model: true
batch_size: 2
num_workers: 8
split_seed: 1

wandb:
    project_name: T2VQA

data:   
    train:
        type: T2VDataset
        args:
            phase: train
            anno_file: /data/TeamMember/lm/sy/project/info.txt
            data_prefix: /data/TeamMember/lm/sy/project/T2VQA-DB
            size: 224
            clip_len: 8
            frame_interval: 2

    eval:
        type: T2VDataset
        args:
            phase: test
            anno_file: /data/TeamMember/lm/sy/project/info.txt
            data_prefix: /data/TeamMember/lm/sy/project/T2VQA-DB
            size: 224
            clip_len: 8
            frame_interval: 2

    t2v:
        type: T2VDataset
        args:
            phase: test
            anno_file: /data/TeamMember/lm/sy/project/info.txt
            data_prefix: /data/TeamMember/lm/sy/project/T2VQA-DB
            size: 224
            clip_len: 8
            frame_interval: 2

model:
    args:
       
        image_size: 224
        clip_len: 8  
 
        llm_model: /home/sy/.cache/modelscope/hub/models/Qwen/Qwen2.5-7B-Instruct
        
     
        clip_weights: /home/sy/.cache/modelscope/hub/models/AI-ModelScope/clip-vit-large-patch14
        
      
        aesthetic_weights: /data/TeamMember/lm/sy/project/models/COVER.pth 
        
        blip_weights: /data/TeamMember/lm/sy/project/models/model_large-002.pth
        use_blip_lora: false
        use_llm_lora: false
            
optimizer:
    lr: !!float 1e-5
    wd: 0.05
        
test_load_path: "/data/TeamMember/lm/sy/project/models/T2VQA-main/pretrained_weights/threeBranch.pth"