name: T2VQA
num_epochs: 30
warmup_epochs: 2.5
save_model: true
batch_size: 8
num_workers: 6
# split_seed: -1
split_seed: 1

wandb:
    project_name: T2VQA

data:   
    train:
        type: T2VDataset
        args:
            phase: train
            # anno_file: /root/autodl-tmp/info_sub5000_train4000.txt
            anno_file: /data/TeamMember/lm/sy/project/info.txt
            data_prefix: /data/TeamMember/lm/sy/project/T2VQA-DB
            size: 224
            clip_len: 8
            frame_interval: 2

    eval:
        type: T2VDataset
        args:
            phase: test
            anno_file: /data/TeamMember/lm/sy/project/info.txt
            data_prefix: /data/TeamMember/lm/sy/project/T2VQA-DB
            size: 224
            clip_len: 8
            frame_interval: 2

    t2v:
        type: T2VDataset
        args:
            phase: test
            anno_file: /data/TeamMember/lm/sy/project/info.txt
            data_prefix: /data/TeamMember/lm/sy/project/T2VQA-DB
            size: 224
            clip_len: 8
            frame_interval: 2



model:
    args:
        med_config: '/data/TeamMember/lm/sy/project/models/T2VQA-main//med_config.json'
        image_size: 224
        nhead: 8
        dropout: 0.1
        nlayers: 6
        embed_dim: 256 
        llm_model: /data/TeamMember/lm/sy/project/models/lmsys/vicuna-7b-v1___1/
        blip_weights: /data/TeamMember/lm/sy/project/models/model_large.pth
        swin_weights: /data/TeamMember/lm/sy/project/models/swin_tiny_patch244_window877_kinetics400_1k.pth
        conv_weights: /data/TeamMember/lm/sy/project/models/convnext_3d_tiny_3.pth
        bert_weights: /data/TeamMember/lm/sy/project/models/bert-base-uncased
        aesthetic_weights: /data/TeamMember/lm/sy/project/models/COVER.pth 
            
optimizer:
    lr: !!float 1e-5
    wd: 0.05
        

test_load_path: "/data/TeamMember/lm/sy/project/models/T2VQA-main/threeBranch.pth"

    
        
